object Versions {

    const val kotlin = "1.7.10"
    const val coroutines = "1.6.1"
    const val serializationJson = "1.3.3"
    const val androidxNavigation = "2.5.0"
    const val androidxLifecycle = "2.2.0"
    const val androidxRoom = "2.4.2"
    const val androidxCore = "1.8.0"
    const val androidxActivity = "1.4.0"
    const val androidxFragment = "1.5.0"
    const val androidxAppcompat = "1.4.2"
    const val androidxMaterial = "1.6.1"
    const val androidxConstraintLayout = "2.1.4"
    const val androidxRecyclerView = "1.2.1"
    const val androidxViewPager2 = "1.0.0"
    const val androidxPaging = "3.1.1"
    const val androidxSwiperefresh = "1.1.0"
    const val androidxWorkmanagerRuntime = "2.7.1"
    const val androidxWorkmanagerHiltWork = "1.0.0"
    const val androidxDataStore = "1.0.0"
    const val daggerHilt = "2.42"
    const val gson = "2.9.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.9.3"
    const val timber = "5.0.1"
    const val glide = "4.13.2"
    const val exoplayer = "2.11.3"
    const val kohii = "1.1.0.2011003"
    const val lottie = "5.0.3"
    const val swipeRevealLayout = "1.4.1"
    const val viewBinding = "1.5.6"
    const val firebaseBom = "30.3.0"
    const val splashScreen = "1.0.0-beta02"

    // plugin
    const val androidGradle = "7.3.1"
    const val kotlinGradle = "1.7.10"
    const val kotlinSerialization = "1.6.20"
    const val hiltGradle = "2.42"
    const val navigationSaveArgs = "2.5.0"
    const val googleServices = "4.3.13"
}